# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Windows Builder

on:
  push:
    branches: [ master, testing ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade 'setuptools<45.0.0'
        pip install pygame
        pip install numpy==1.19.3
        pip install cython
        pip install cx-freeze
        pip install pyinstaller
        pip install yapf
    - name: build caramel-recolor-cython
      run: |
        cd caramel-recolor-cython
        python setup.py install
        cd ..
    - name: build with pyinstaller
      run: |
        cxfreeze -c main.py --target-dir dist/ghcaramel --include-files=data,design,image,music,credits.md,history.md,LICENSE,README.md -s --target-name=ghcaramel --packages=pygame,numpy,pbgerecolor
    - name: Upload the file
      uses: actions/upload-artifact@v1
      with:
        name: ghcwin
        path: build/
